"""fix

Revision ID: d24ff6d1a8b3
Revises: 22997731c0df
Create Date: 2019-12-17 23:15:22.699470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24ff6d1a8b3'
down_revision = '22997731c0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'password_hash')
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.add_column('roles', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
